export const ACTIVATE_LINK                  = 'ACTIVATE_LINK';
export const CHANGE_MOBILEMENU_VISIBILITY   = 'CHANGE_MOBILEMENU_VISIBILITY';
export const CHANGE_QUANT_SUBCATEGORIES     = 'CHANGE_QUANT_SUBCATEGORIES';
export const CHANGE_SUBMENU_VISIBILITY      = 'CHANGE_SUBMENU_VISIBILITY';
export const PAGINATION_CHANGE_PAGE         = 'PAGINATION_CHANGE_PAGE';
export const PAGINATION_CHANGE_TOTAL_OBJECT = 'PAGINATION_CHANGE_TOTAL_OBJECT';
export const UPDATE_LIST_CATEGORIES         = 'UPDATE_LIST_CATEGORIES';
export const UPDATE_LIST_MENU               = 'UPDATE_LIST_MENU';